# Generated by Django 3.2.6 on 2021-11-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_alter_repuesto_tipo'),
        ('taller', '0004_alter_repuesto_tipo'),
    ]

    operations = [
    ]
