# Generated by Django 3.2.6 on 2021-11-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_alter_repuesto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomaterial',
            name='unidad_medida',
            field=models.PositiveSmallIntegerField(choices=[(1, 'g'), (2, 'CM3'), (4, 'Unidad/es'), (6, 'Metro/s'), (7, 'Metro2')]),
        ),
    ]
