# Generated by Django 3.2.6 on 2021-11-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_merge_20211101_1643'),
        ('taller', '0006_alter_repuesto_tipo'),
    ]

    operations = [
    ]
