# Generated by Django 3.2.6 on 2021-11-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_alter_tipomaterial_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tareas',
            field=models.ManyToManyField(related_name='empleados', to='taller.TipoTarea'),
        ),
    ]
