# Generated by Django 3.2.6 on 2021-11-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_merge_20211108_1642'),
        ('taller', '0008_alter_empleado_tareas'),
    ]

    operations = [
    ]
