# Generated by Django 3.2.6 on 2021-12-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_merge_20211111_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoRepuesto',
        ),
    ]
