# Generated by Django 3.2.6 on 2022-02-22 22:00

from django.db import migrations, models
import taller.models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0010_delete_tiporepuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(validators=[taller.models.validar_anio]),
        ),
    ]
