# Generated by Django 3.2.6 on 2022-05-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0011_alter_vehiculo_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomaterial',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
