# Generated by Django 3.2.6 on 2022-07-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0013_alter_tipomaterial_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotarea',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
