# Generated by Django 3.2.6 on 2022-07-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0014_alter_tipotarea_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
