# Generated by Django 3.2.6 on 2022-09-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0015_auto_20220718_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
