# Generated by Django 3.2.6 on 2022-10-24 22:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taller.models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0016_alter_material_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='taller.tipomaterial'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='anio',
            field=models.PositiveSmallIntegerField(validators=[taller.models.anio_valido]),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modelos', to='taller.marca'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='taller.modelo'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='taller.tipotarea'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehiculos', to='taller.cliente'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='taller.modelo'),
        ),
    ]
