# Generated by Django 3.2.6 on 2023-03-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0017_auto_20221024_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
