# Generated by Django 3.2.6 on 2021-09-29 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taller', '0002_alter_repuesto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('exitosa', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taller.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_de_trabajo', to='taller.material')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.DateTimeField(auto_now_add=True)),
                ('ingreso', models.DateTimeField(blank=True, null=True)),
                ('egreso', models.DateTimeField(blank=True, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Creada'), (1, 'Activa'), (3, 'Pausada'), (2, 'Cancelada'), (4, 'Realizada'), (5, 'Facturada')], default=0)),
                ('materiales', models.ManyToManyField(through='ordenes.MaterialOrdenDeTrabajo', to='taller.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.CharField(max_length=200)),
                ('validez', models.PositiveIntegerField(default=60)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='taller.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RepuestoOrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_repuestos', to='ordenes.ordendetrabajo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_de_trabajo', to='taller.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_repuestos', to='ordenes.presupuesto')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='taller.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='taller.material')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_materiales', to='ordenes.presupuesto')),
            ],
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='materiales',
            field=models.ManyToManyField(through='ordenes.PresupuestoMaterial', to='taller.Material'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='ordenes.ordendetrabajo'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='repuestos',
            field=models.ManyToManyField(through='ordenes.PresupuestoRepuesto', to='taller.Repuesto'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tareas',
            field=models.ManyToManyField(related_name='presupuestos', to='taller.Tarea'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='taller.vehiculo'),
        ),
        migrations.CreateModel(
            name='PlanillaDePintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_de_color', models.CharField(max_length=100)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.detalleordendetrabajo')),
            ],
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='repuestos',
            field=models.ManyToManyField(through='ordenes.RepuestoOrdenDeTrabajo', to='taller.Repuesto'),
        ),
        migrations.AddField(
            model_name='materialordendetrabajo',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_materiales', to='ordenes.ordendetrabajo'),
        ),
        migrations.CreateModel(
            name='DetallePlanillaDePintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.planilladepintura')),
            ],
        ),
        migrations.AddField(
            model_name='detalleordendetrabajo',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.ordendetrabajo'),
        ),
        migrations.AddField(
            model_name='detalleordendetrabajo',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.tarea'),
        ),
    ]
