# Generated by Django 3.2.6 on 2021-10-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Creada'), (1, 'Activa'), (7, 'Iniciada'), (3, 'Pausada'), (2, 'Cancelada'), (4, 'Realizada'), (5, 'Facturada'), (6, 'Finalizada')], default=0),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='turno',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planilladepintura',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas', to='ordenes.detalleordendetrabajo'),
        ),
    ]
