# Generated by Django 3.2.6 on 2021-09-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleordendetrabajo',
            name='detalles',
        ),
        migrations.AddField(
            model_name='detalleordendetrabajo',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
