# Generated by Django 3.2.6 on 2021-12-03 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0010_delete_tiporepuesto'),
        ('ordenes', '0004_auto_20211202_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoorden',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='taller.cliente'),
        ),
        migrations.AlterField(
            model_name='turnoorden',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='taller.vehiculo'),
        ),
    ]
