# Generated by Django 3.2.6 on 2022-02-02 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_auto_20211202_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
