# Generated by Django 3.2.6 on 2022-02-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_presupuesto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Creado'), (1, 'Cancelado'), (2, 'Confirmado')], default=0),
        ),
    ]
