# Generated by Django 3.2.6 on 2022-05-30 18:24

from django.db import migrations, models
import ordenes.models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_alter_presupuestorepuesto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='turno',
            field=models.DateTimeField(validators=[ordenes.models.fecha_es_futura]),
        ),
        migrations.AlterField(
            model_name='presupuestomaterial',
            name='cantidad',
            field=models.PositiveBigIntegerField(validators=[ordenes.models.cantidad_positiva]),
        ),
    ]
