# Generated by Django 3.2.6 on 2022-05-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0013_alter_tipomaterial_nombre'),
        ('ordenes', '0009_auto_20220530_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='materiales',
            field=models.ManyToManyField(blank=True, through='ordenes.MaterialOrdenDeTrabajo', to='taller.Material'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='repuestos',
            field=models.ManyToManyField(blank=True, through='ordenes.RepuestoOrdenDeTrabajo', to='taller.Repuesto'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='materiales',
            field=models.ManyToManyField(blank=True, through='ordenes.PresupuestoMaterial', to='taller.Material'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='repuestos',
            field=models.ManyToManyField(blank=True, through='ordenes.PresupuestoRepuesto', to='taller.Repuesto'),
        ),
    ]
