# Generated by Django 3.2.6 on 2022-05-30 18:53

from django.db import migrations, models
import django.db.models.deletion
import ordenes.models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0013_alter_tipomaterial_nombre'),
        ('ordenes', '0010_auto_20220530_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='materiales',
            field=models.ManyToManyField(through='ordenes.MaterialOrdenDeTrabajo', to='taller.Material'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='repuestos',
            field=models.ManyToManyField(through='ordenes.RepuestoOrdenDeTrabajo', to='taller.Repuesto'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='materiales',
            field=models.ManyToManyField(through='ordenes.PresupuestoMaterial', to='taller.Material'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='repuestos',
            field=models.ManyToManyField(through='ordenes.PresupuestoRepuesto', to='taller.Repuesto'),
        ),
        migrations.AlterField(
            model_name='presupuestomaterial',
            name='cantidad',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[ordenes.models.cantidad_positiva]),
        ),
        migrations.AlterField(
            model_name='presupuestomaterial',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='taller.material'),
        ),
        migrations.AlterField(
            model_name='presupuestorepuesto',
            name='cantidad',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[ordenes.models.cantidad_positiva]),
        ),
        migrations.AlterField(
            model_name='presupuestorepuesto',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='taller.repuesto'),
        ),
    ]
