# Generated by Django 3.2.6 on 2022-07-14 21:17

from django.db import migrations, models
import django.db.models.deletion
import ordenes.models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0013_alter_tipomaterial_nombre'),
        ('ordenes', '0012_auto_20220714_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestomaterial',
            name='cantidad',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[ordenes.models.cantidad_positiva]),
        ),
        migrations.AlterField(
            model_name='presupuestomaterial',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='taller.material'),
        ),
        migrations.AlterField(
            model_name='presupuestorepuesto',
            name='cantidad',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[ordenes.models.cantidad_positiva]),
        ),
        migrations.AlterField(
            model_name='presupuestorepuesto',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='taller.repuesto'),
        ),
    ]
