# Generated by Django 3.2.6 on 2022-07-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0013_alter_tipomaterial_nombre'),
        ('ordenes', '0013_auto_20220714_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='materiales',
            field=models.ManyToManyField(blank=True, through='ordenes.PresupuestoMaterial', to='taller.Material'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='repuestos',
            field=models.ManyToManyField(blank=True, through='ordenes.PresupuestoRepuesto', to='taller.Repuesto'),
        ),
    ]
