# Generated by Django 3.2.6 on 2022-07-14 21:58

from django.db import migrations, models
import ordenes.models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0015_auto_20220714_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestomaterial',
            name='cantidad',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, validators=[ordenes.models.cantidad_positiva]),
        ),
    ]
