# Generated by Django 3.2.6 on 2022-07-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0016_alter_presupuestomaterial_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestomaterial',
            name='cantidad',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestorepuesto',
            name='cantidad',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
