# Generated by Django 3.2.6 on 2022-07-28 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0015_auto_20220718_1725'),
        ('ordenes', '0017_auto_20220718_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='ampliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalleordendetrabajo',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detallesorden', to='taller.tarea'),
        ),
    ]
