# Generated by Django 3.2.6 on 2022-08-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0018_auto_20220728_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Creada'), (1, 'Activa'), (7, 'Iniciada'), (3, 'Pausada'), (2, 'Cancelada'), (4, 'Realizada'), (5, 'Facturada'), (6, 'Finalizada'), (8, 'Pagada')], default=0),
        ),
    ]
