# Generated by Django 3.2.6 on 2022-09-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0019_alter_ordendetrabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
