# Generated by Django 3.2.6 on 2022-10-24 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0017_auto_20221024_1913'),
        ('ordenes', '0020_presupuesto_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='presupuestos', to='taller.vehiculo'),
        ),
    ]
