# Generated by Django 3.2.6 on 2022-12-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0022_auto_20221125_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordendetrabajo',
            options={'permissions': [('can_registrar_ingreso', 'Puede registrar el ingreso de un vehículo al taller'), ('can_registrar_egreso', 'Puede registrar el egreso de un vehículo al taller'), ('can_asignar_trabajo', 'Puede asignar trabajo a empleados')]},
        ),
    ]
