# Generated by Django 3.2.6 on 2022-12-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0024_auto_20221203_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='egreso',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='ingreso',
            field=models.DateTimeField(null=True),
        ),
    ]
