# Generated by Django 3.2.6 on 2022-12-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0025_auto_20221205_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleordendetrabajo',
            options={'permissions': [('can_asignar_trabajo', 'Puede asignar trabajo a empleados'), ('can_ver_asignados', 'Puede ver listado de trabajos asignados'), ('can_ver_sin_finalizar', 'Puede ver listado de trabajos sin finalizar'), ('can_ver_finalizados', 'Puede ver listado de trabajos finalizados'), ('can_ver_todos', 'Puede ver todos de trabajos')]},
        ),
        migrations.AlterModelOptions(
            name='ordendetrabajo',
            options={'permissions': [('can_registrar_ingreso', 'Puede registrar el ingreso de un vehículo al taller'), ('can_registrar_egreso', 'Puede registrar el egreso de un vehículo al taller')]},
        ),
    ]
