# Generated by Django 3.2.6 on 2022-03-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.PositiveBigIntegerField(choices=[(0, 'Creada'), (1, 'Activa'), (2, 'Cancelada'), (3, 'Realizada'), (4, 'Vencida')], default=0),
        ),
    ]
