# Generated by Django 3.2.6 on 2022-07-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cuotas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
