# Generated by Django 3.2.6 on 2022-08-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_alter_factura_cuotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cuotas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.PositiveBigIntegerField(choices=[(0, 'Creada'), (1, 'Activa'), (2, 'Cancelada'), (3, 'Pagada'), (4, 'Vencida')], default=0),
        ),
    ]
